### ISSUE TITLE
Abbreviation substitutions

### ISSUE THREAD

**Issue by pods4life** [EA-Pods-Team/pdf-bullets#5]
When typing out "for" it replaces with f/ but with a space following, I cannot delete the space because it will just think it is one big word.

Also does not abbreviate words in abbreviation list if I add a s at the end, or things like reprogramming.

**Comment by ckhordiasma** [comment]
resolved "for" issue. in the abbreviations sheet, use "for " (space at the end) to make the space go away.

for the plural/word variants thing, for now you will need to just add the plural into the abbreviations list.

**Comment by ckhordiasma** [comment]
relevant commit with final changes: 1f61851baeb965bde47e0fb465f1659925d606cb
